cache:
  directories:
    - node_modules
    - ~/.npm
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: apiKey # desde heroku
  app: platzi-store-backend
  on:
    repo: danibarria/platzi-store-backend

git:
  depth: 3
language: node_js
node_js:
  - "12"
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - johansarmiento_21@live.com
script:
  - "yarn test"
